apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
  namespace: bluegreen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bluegreen
      color: blue
  template:
    metadata:
      labels:
        app: bluegreen
        color: blue
    spec:
      containers:
        - name: web
          image: loksjain25/bluegreen:blue-0
          imagePullPolicy: Always
          env:
            - name: COLOR
              value: "blue"
            - name: VERSION
              value: "blue-0"
            - name: APP_NAME
              value: "bluegreen-demo"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
